"""empty message

Revision ID: 40f364a0e47c
Revises: d80c6e40ffba
Create Date: 2023-12-21 14:13:19.967516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f364a0e47c'
down_revision = 'd80c6e40ffba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reps', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_column('sets')
        batch_op.drop_column('weight')
        batch_op.drop_column('reps')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('weight')
        batch_op.drop_column('sets')
        batch_op.drop_column('reps')

    # ### end Alembic commands ###
