"""empty message

Revision ID: 55c0aa899796
Revises: 37b5be6ce52b
Create Date: 2023-12-21 13:15:54.386630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c0aa899796'
down_revision = '37b5be6ce52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('workout_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_logs_workout_id_workouts'), 'workouts', ['workout_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_logs_exercise_id_exercises'), 'exercises', ['exercise_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_logs_exercise_id_exercises'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_logs_workout_id_workouts'), type_='foreignkey')
        batch_op.drop_column('workout_id')
        batch_op.drop_column('exercise_id')

    # ### end Alembic commands ###
