"""empty message

Revision ID: 8a515b960983
Revises: 55c0aa899796
Create Date: 2023-12-21 13:33:01.174133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a515b960983'
down_revision = '55c0aa899796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_logs_workout_id_workouts', type_='foreignkey')
        batch_op.drop_constraint('fk_logs_exercise_id_exercises', type_='foreignkey')
        batch_op.drop_column('exercise_id')
        batch_op.drop_column('workout_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_logs_exercise_id_exercises', 'exercises', ['exercise_id'], ['id'])
        batch_op.create_foreign_key('fk_logs_workout_id_workouts', 'workouts', ['workout_id'], ['id'])

    # ### end Alembic commands ###
