"""empty message

Revision ID: 9b85a09bb8c5
Revises: 8d9dc5ae2d60
Create Date: 2023-12-14 16:19:51.726529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b85a09bb8c5'
down_revision = '8d9dc5ae2d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exercises_log_id_logs', type_='foreignkey')
        batch_op.drop_column('log_id')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_logs_exercise_id_exercises', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_logs_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('exercise_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_logs_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_logs_exercise_id_exercises', 'exercises', ['exercise_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_exercises_log_id_logs', 'logs', ['log_id'], ['id'])

    # ### end Alembic commands ###
